# Stage 1: Build Angular SSR App
FROM node:20 AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build
RUN npm run serve:ssr:BaseApp --output-path dist/base-app

# Stage 2: Serve the SSR App
FROM node:20-slim
WORKDIR /app

COPY --from=builder /app/dist/base-app ./dist/base-app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./

EXPOSE 4000

CMD ["node", "dist/base-app/server/server.mjs"]
